ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER kh_jwh IDENTIFIED BY "oracle_jwh123A";

GRANT RESOURCE, CONNECT TO kh_jwh;

ALTER USER kh_jwh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;;