-- SQL 01 1번 문제 학과 이름과 계열 표시 "학과 명" "계열 "

SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS 계열
FROM TB_DEPARTMENT td ;

-- 2번 문제 학과의 정원을 출력

SELECT DEPARTMENT_NAME ||'의 정원은 '||CAPACITY ||'명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT t;

-- 3번 문제  국어국문학과에 다니는 여학생 중 휴학중인 학생
-- 학과코드는 학과 테이블 을 조회해서 찾아내자

SELECT STUDENT_NAME FROM TB_STUDENT ts 
WHERE DEPARTMENT_NO = '001'
AND ABSENCE_YN ='Y' AND SUBSTR(STUDENT_SSN,8,1) ='2'; 

-- 4번장기 연체자를 찾자 
SELECT STUDENT_NAME  FROM TB_STUDENT ts 
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC ;

-- 5번 문제 입학정원 20명 이상 30명 이하인 학과 이름  계열
SELECT DEPARTMENT_NAME , CATEGORY 
FROM TB_DEPARTMENT td 
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6번 문제 총장의 이름을 알아낼 수 있는 방법
SELECT  PROFESSOR_NAME
FROM TB_PROFESSOR tp  
WHERE DEPARTMENT_NO IS NULL;

-- 7번 문제 학과가 없는 학생
SELECT *
FROM TB_STUDENT ts 
WHERE DEPARTMENT_NO IS NULL;

-- 8번 문제 수강신청 선수과목 존재하는 과목 찾기
SELECT CLASS_NO
FROM TB_CLASS 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9번 문제 춘 대학 어떤 계열이 있니?
SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT td ;

-- 10번 문제  02학번 전주 거주자들의 모임 만들기 휴학생을 제외하고 재학중인 학생의 
-- 학번 이름 주민 번호 출력
 
SELECT STUDENT_NO ,STUDENT_NAME ,STUDENT_SSN 
FROM TB_STUDENT ts 
WHERE ABSENCE_YN ='N' AND STUDENT_ADDRESS LIKE '전주%'
AND EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002; 

-------------------------------------------------------------------

-- SQL 02 1번 문제 영문과 학생들 학번과 이름 입학년도가 빠른 순으로 정렬

SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, ENTRANCE_DATE AS 입학년도
FROM TB_STUDENT ts 
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2번 문제  대학교수 중 이름이 세글자가 아닌 교수 찾기
SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR tp 
WHERE LENGTH(PROFESSOR_NAME) !=3;

-- 3번 문제 남자 교수들 이름과 나우를 출력 나이가 적은 사람에서 많은 사람 순서로 화면 출력
SELECT PROFESSOR_NAME AS 교수이름,
FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE('19'||
SUBSTR(PROFESSOR_SSN,1,6),'YYYYMMDD'))/12) AS 나이
FROM TB_PROFESSOR 
WHERE SUBSTR(PROFESSOR_SSN,8,1) ='1'
ORDER BY 2;

-- 4번 성을 제외하고 교수 이름만 출력
SELECT SUBSTR(PROFESSOR_NAME ,2) AS 이름
FROM TB_PROFESSOR tp ;

-- 5번 재수생 입학자 19살에 입학하면 재수한게 아님
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT (YEAR FROM ENTRANCE_DATE) -
LPAD(SUBSTR(STUDENT_SSN,1,2),4,'19') >=20;

-- 6번 20년도 크리스마스는 무슨요일?
SELECT TO_CHAR(TO_DATE(20201225),'DAY') FROM DUAL;

-- 7번  몇년도를 나타낼까? 
SELECT TO_DATE('99/10/11','YY/MM/DD') FROM DUAL;
SELECT TO_DATE('49/10/11','YY/MM/DD') FROM DUAL;
SELECT TO_DATE('99/10/11','RR/MM/DD') FROM DUAL;
SELECT TO_DATE('49/10/11','RR/MM/DD') FROM DUAL;

-- 8번 2000년도 이전 학번 검색
SELECT STUDENT_NO ,STUDENT_NAME
FROM TB_STUDENT ts 
WHERE STUDENT_NO NOT LIKE 'A%';

-- 9번 한아름 학생 학점 평균
SELECT ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10번 학과별 학생수를 구하여 학과번호 학생수 명 형태로 
SELECT DEPARTMENT_NO AS 학과명, COUNT(*) "학생 수 "
FROM TB_STUDENT ts 
GROUP BY DEPARTMENT_NO 
ORDER BY 1;

-- 11 지도 교수가 없는 학생 수

SELECT COUNT(*)
FROM TB_STUDENT ts 
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12번 학번 A112113인 김고운 학생 년도 별 평점 구하기
SELECT SUBSTR(TERM_NO,1,4)AS 년도,ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4) 
ORDER BY 1;

--13 번 학과별 휴학생 수 

SELECT DEPARTMENT_NO AS 학과명,
COUNT(DECODE(ABSENCE_YN,'Y','Y')) AS "휴학생 수 "
FROM TB_STUDENT ts 
GROUP BY DEPARTMENT_NO 
ORDER BY 1;

-- 14번 동명이인 합
SELECT STUDENT_NAME AS 동명이인, COUNT(*) AS "동명인 수"
FROM TB_STUDENT ts 
GROUP BY STUDENT_NAME 
HAVING COUNT(*) > 1
ORDER BY 1;

--15번  학번 A112113인 김고운 학생 학기별 평점과 년도 별 누적평점 총점

SELECT NVL(SUBSTR(TERM_NO,1,4),' ')AS 년도,
NVL(SUBSTR(TERM_NO,5,2),' ')AS 학기,
ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP (SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2));

----------------------------------------------------------------------

--SQL 03 1번문제 학생이름 주소지 표시

SELECT STUDENT_NAME AS "학생 이름" , STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT ts 
ORDER BY 1;


-- 2번 문제   
SELECT STUDENT_NAME , STUDENT_SSN
FROM TB_STUDENT ts
WHERE ABSENCE_YN= 'Y'
ORDER BY 2 DESC;

--3번 문제 
SELECT STUDENT_NAME AS 학생이름 , STUDENT_NO AS 학번,
STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT ts 
WHERE STUDENT_NO LIKE '9%' 
AND STUDENT_ADDRESS LIKE '%경기도%'
OR STUDENT_ADDRESS LIKE '%강원도%'
ORDER BY 1;

-- 4번 법학과 교수
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR tp 
WHERE DEPARTMENT_NO ='005'
ORDER BY PROFESSOR_SSN ;

-- 5번 C3118100 과목을 수강항 학생들의 학점 조회 
SELECT STUDENT_NO, TO_CHAR(POINT,'FM9.00') AS 학점
FROM TB_GRADE  
WHERE CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY POINT DESC, STUDENT_NO ;

-- 6번 문제 학생 번호, 학생 이름,학과 이름을 학생
-- 학생 이름으로 오름차순 정렬하여 출력하는 SQL문을 작성하시오
SELECT STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
ORDER BY 2;

-- 7번 춘 기술대학교의 과목 이름과 과목의 학과 이름을 출력하는 SQL문장을 작성하시오.
SELECT CLASS_NAME,DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO);

-- 8번 . 과목별 교수 이름을 찾으려고 한다. 과목 이름과 교수 이름을 출력하는 SQL문을 작성하시오.
--(기존 워크북 PDF에 나타난 조회 결과는 DB 버전이 낮아 현재와 조회 방식이 다름.
--결과 행의 수만 동일하게 조회하자)

SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS tc 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO);

--9. 8번의 결과 중 '인문 사회' 계열에 속한 과목의 교수 이름을 찾으려고 한다.
--이에 해당하는 과목 이름과 교수 이름을 출력하는 SQL문을 작성하시오.

SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS tc 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR p USING (PROFESSOR_NO)
JOIN TB_DEPARTMENT d ON (p.DEPARTMENT_NO = d.DEPARTMENT_NO) 
WHERE CATEGORY = '인문사회';

--10. '음악학과' 학생들의 평점을 구하려고 한다. 음악학과 학생들의 
--"학번", "학생 이름", "전체 평점"을 출력하는
--SQL 문장을 작성하시오.
--(단, 평점은 소수점 1자리까지만 반올림하여 표시한다.)

SELECT STUDENT_NO AS 학번 ,STUDENT_NAME AS "학생 이름",
ROUND(AVG(POINT),1) AS "전체평점"
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO ,STUDENT_NAME 
ORDER BY 학번;

 --11. 학번이 A313047인 학생이 학교에 나오고 있지 않다. 
 --지도 교수에게 내용을 전달하기 위한 학과 이름, 학생
--이름과 지도 교수 이름이 필요하다. 이때 사용할 SQL문을 작성하시오.
--단, 출력헤더는 “학과이름”, “학생이름”, “지도교수이름” 으로 출력되도록 한다

SELECT DEPARTMENT_NAME AS 학과이름 , STUDENT_NAME AS 학생이름, 
PROFESSOR_NAME AS 지도교수이름
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO= PROFESSOR_NO )
WHERE STUDENT_NO = 'A313047';

--12. 2007년도에 '인간관계론' 과목을 수강한 학생을 찾아
--학생이름과 수강학기를 표시하는 SQL 문장을 작성하시오

SELECT STUDENT_NAME,TERM_NO AS TERM_NAME
FROM TB_STUDENT ts 
JOIN TB_GRADE tg USING(STUDENT_NO)
JOIN TB_CLASS tc USING(CLASS_NO)
WHERE TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론';

--13. 예체능 계열 과목 중 과목 담당교수를 한 명도 배정받지 못한 과목을 찾아
--그 과목 이름과 학과 이름을 출력하는 SQL 문장을 작성하시오.
--(기존 워크북 PDF에 나타난 조회 결과는 D

SELECT CLASS_NAME,DEPARTMENT_NAME
FROM TB_CLASS tc 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR tcp USING (CLASS_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;

--14. 춘 기술대학교 서반아어학과 학생들의 지도교수를 게시하고자 한다. 
--학생이름과 지도교수 이름을 찾고 만일 지도 교수가 없는 학생일 경우
--"지도교수 미지정"으로 표시하도록 하는 SQL 문을 작성하시오.
--단 출력헤더는 "학생이름", "지도교수"로 표시하며 고학번 학생이 먼저 표시되도록 한다

SELECT STUDENT_NAME AS 학생이름 , NVL(PROFESSOR_NAME,'지도교수 미지정') AS 지도교수
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO= PROFESSOR_NO )
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;

--15. 휴학생이 아닌 학생 중 평점이 4.0 이상인 학생을 찾아
 --그 학생의 학번, 이름, 학과, 이름, 평점을 출력하는SQL문을 작성하시오

SELECT STUDENT_NO AS 학번,STUDENT_NAME AS 이름,
DEPARTMENT_NAME AS 학과이름 , ROUND(AVG(POINT),8)
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN ='N'
GROUP BY STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
HAVING ROUND(AVG(POINT),8)>= 4.0 ORDER BY STUDENT_NO ;

--16. 환경조경학과 전공과목들의 과목 별 평점을 파악할 수 있는 SQL 문을 작성하시오.

SELECT CLASS_NO ,CLASS_NAME, TRUNC(AVG(POINT),8)
FROM TB_CLASS tc 
NATURAL JOIN TB_GRADE tg 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO ,CLASS_NAME
ORDER BY CLASS_NO;

--17. 춘 기술대학교에 다니고 있는 최경희 학생과 같은 과 학생들의 
--이름과 주소를 출력하는 SQL 문을작성하시오.
 
SELECT STUDENT_NAME ,STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT 
						WHERE STUDENT_NAME = '최경희');

--18. 국어국문학과에서 총 평점이 가장 높은 학생의 이름과 학번을 표시하는 SQL문을 작성하시오
SELECT STUDENT_NO, STUDENT_NAME
FROM 
(SELECT STUDENT_NO , STUDENT_NAME FROM TB_STUDENT 
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO , STUDENT_NAME 
ORDER BY AVG(POINT) DESC)
WHERE ROWNUM=1;


--19. 춘 기술대학교의 "환경조경학과"가 속한 같은 계열 학과들의 
--학과 별 전공과목 평점을 파악하기 위한적절한 SQL문을 찾아내시오.
--단, 출력헤더는 "계열 학과명", "전공평점"으로 표시되도록 하고,
 --평점은 소수점 한자리까지만 반올림하여표시되도록 한다


SELECT DEPARTMENT_NAME "계열 학과명", 
ROUND(AVG(POINT), 1) 전공평점 FROM TB_DEPARTMENT 
JOIN TB_CLASS USING(DEPARTMENT_NO) 
JOIN TB_GRADE USING(CLASS_NO) 
WHERE CATEGORY = (
    SELECT CATEGORY FROM TB_DEPARTMENT 
    WHERE DEPARTMENT_NAME = '환경조경학과')
AND CLASS_TYPE LIKE '전공%' 
GROUP BY DEPARTMENT_NAME ORDER BY DEPARTMENT_NAME;
